### ISSUE TITLE
PVC in Oncology

### ISSUE THREAD

**Issue by madyankoh** [UCL/PETPVC#10]
Hello Dear Thomas

How can I use the PVC Regain-Based methods in oncology?

Thanks

**Comment by bathomas** [comment]
Hi @madyankoh, 

The ways you might apply PVC in oncology depends on your application. Can you give a specific example of what you would like to do?

Kind regards,

Ben

**Comment by madyankoh** [comment]
Thank you for the reply.

When I want to apply PVC (for example MTC) on WB PET with a mask file, I received  this error (attached file).

![error](https://cloud.githubusercontent.com/assets/26072431/23569477/ba4cc936-0074-11e7-8f06-b9619f3f8f10.JPG)


Thanks
madyankoh

**Comment by bathomas** [comment]
Hi,

It looks like your PET and mask have different voxel sizes and different origins. Both images need to be in the same space. You need to resample one of them to match the other.  I presume your PET voxels are 5.46x5.46x3.27mm and the mask voxels are 0.97x0.97x3.27mm? I would recommend upsampling the PET to match the mask. There are examples in ITK of how to resample images. Make sure you use linear interpolation during resampling if you are changing the PET.

Kind regards,

Ben

**Comment by bathomas** [comment]
Hi @madyankoh,

Did you manage to figure this out?

Kind regards,

Ben

**Comment by madyankoh** [comment]
Hi Dear Thomas
Sorry for delay in response and thanks for your email.
I applied PVC with STC,  VC and RL methods on Oncolocal PET  image but
couldn't use other method while PET  and mask image have same voxel size.
Best wishes

**Comment by bathomas** [comment]
Hi @madyankoh,

For the other methods the mask needs to be in 4D. Could this be the problem?

Kind regards,

Ben

**Comment by madyankoh** [comment]
Hi Dear Dr. Thomas
Yes, I read your post how to make it but I couldn't make 4D mask.
Thanks for responding
Best wishes.
