### ISSUE TITLE
libitk=5.3 required when install from conda-forge

### ISSUE THREAD

**Issue by gschramm** [UCL/PETPVC#100]
Hi all,

thanks a lot for making `petpvc` open source :)

I just tried to install from conda-forge (on MacOS and Windows) via:
```
conda create -n petpvc -c conda-forge petpvc
```

In both cases I get errors when running `petpvc` complaing that a few ITK libs of version 5.3 cannot be found.

Downgrading `libtik` to `v5.3` solves the problem.

Georg

**Comment by KrisThielemans** [comment]
Indeed, see #98. Unfortunately, I'm not the owner of the petpvc-feedstock.

**Comment by gschramm** [comment]
I see. would be nice to add a note in the install instructions from conda-forge (if installation from conda-forge should be encouraged).
