### ISSUE TITLE
PETPVC on PET reconstructed with FBP

### ISSUE THREAD

**Issue by Bahri-M-A** [UCL/PETPVC#13]
Dear Thomas,

We have recently tried PETpvc tool on FDG PET images reconstructed with FBP algorithm, but unfortunately we have got a white image for the MG, MTC, IY, and LABBE methods.
Would you have an explanation for this kind of issue? Do you think it might due to the negative values of PET images?

Best Regards,
Mohamed

**Comment by bathomas** [comment]
Dear Mohamed, 

The negative values are not necessarily a problem. When you say 'white image', do you mean an image of all zeros or something else. Please could you explain what mask image you used? 3D or 4D? What values do the mask regions have?

Kind regards,

Ben

**Comment by Bahri-M-A** [comment]
Many thanks for your answer.
The obtained images were zeros (see attached file "image number 4"). The used mask is a 4D image (WM + GM + CSF). These masks (attached file "1,2,3") were obtained using the spm segmentation of the structural MRI image (values between 0 and 1).
![results](https://cloud.githubusercontent.com/assets/3977392/26415236/1651b890-40b2-11e7-9a2c-cd208a4d8ae3.png)
Thank you,
Mohamed

**Comment by bathomas** [comment]
Hi,

The brain looks close to the edge of the image in the transaxial plane. I would recommend adding the background as a region too (GM+WM+CSF) - 1. Then try applying MTC or IY. What happens then?

**Comment by Bahri-M-A** [comment]
Dear Thomas,

With the background as a forth region calculated as (GM+WM+CSF) - 1 the IY method does not work (see the following error:
% ---------------------------------
➜  pvc petpvc -i rrnsCOENEN_AverageTW_PET.nii -m Mask_tissues_4D.nii -o PETpvc_IY.nii --pvc IY -x 6.0 -y 6.0 -z 6.0
Performing iterative Yang...
sum in region 1 = 617462
sum in region 2 = 461294
sum in region 3 = 426752

[Error]	failure applying iY on: rrnsCOENEN_AverageTW_PET.nii

itk::ExceptionObject (0x2fc5640)
Location: "void petpvc::FuzzyCorrectionFilter<TImage>::GenerateData() [with TImage = itk::Image<float, 4u>]" 
File: /home/bahri/Documents/Codes/PETPVC/lib/petpvcFuzzyCorrectionFilter.txx
Line: 126
Description: itk::ERROR: FuzzyCorrFilter(0x2f9e5d0): Region 4contains negative voxels in mask. Remove this region.
% -------------------------------------------------------------------------------------------------------------
however, the MTC method gave an image with very small values (see attached file).
![results_1](https://cloud.githubusercontent.com/assets/3977392/26487250/034fed18-41ff-11e7-89c5-cf6d3c356b2d.png)
I also tried with the background calculated as 1 - (MG+WM+CSF), the IY method seems to give a correct results but MTC provide the same image (very low values : see attached file).
![results_2](https://cloud.githubusercontent.com/assets/3977392/26487413/b6a0ac4a-41ff-11e7-934e-577a040594f0.png)
 
Many Thanks,

Mohamed

**Comment by bathomas** [comment]
My apologies. I meant 1-(GM+WM+CSF). could you try that?

Ben

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by Bahri-M-A** [comment]
Dear Thomas,
The second figure of my last email shows the results of the results of the IY and MTC methods as sub-figures 5 and 6, respectively. These results were obtained using the 1-(GM+WM+CSF) as background mask. As you can see, the results of the MTC method is not good. 
Best regards,
Mohamed

**Comment by bathomas** [comment]
Dear Mohamed,

Would you be willing to share the nifti files via Dropbox or similar? If so, my email address is b.a.thomas [at] ucl.ac.uk. I can then take a look. I assume you are using a PSF of 6mm.

Kind regards,

Ben
