### ISSUE TITLE
Publication reference

### ISSUE THREAD

**Issue by alexsavio** [UCL/PETPVC#2]
Hi,

As I told you a few months ago, I had a wrapper for PETPVC for nipype.

I suggested to them a [PR](https://github.com/nipy/nipype/issues/1332) and they agreed.

It would be nice to add to the wrapper code some reference to PETPVC or even a publication reference. Do you have any suggestion for this?

Thank you!

**Comment by bathomas** [comment]
Hi,

The software paper is still under review. This paper:

K. Erlandsson, I. Buvat, P. H. Pretorius, B. A. Thomas, and B. F. Hutton,
“A review of partial volume correction techniques for emission tomography
and their applications in neurology, cardiology and oncology,” Phys. Med.
Biol., vol. 57, no. 21, p. R119, 2012.

describes the theory behind most the methods that were implemented though.

Kind regards,

Ben

**Comment by alexsavio** [comment]
Hi Ben,

Do you mind if I put this reference for now and when you put the software paper reference in this repository I update the code in nipype?

Thanks

Best,
Alex

**Comment by bathomas** [comment]
Fine by me.

Kind regards,

Ben
