### ISSUE TITLE
PETPVC Starter 

### ISSUE THREAD

**Issue by ELENI93** [UCL/PETPVC#22]
Dear all, 

I am currently working on my dissertation project trying to compensate for PVE on SPECT/CT and PET/CT images. The idea of the project is to use some of PETPVC algorithms for the corrections. I would like to know if there is any tutorial or any kind of documentation to help starters with the toolbox, as I have no experience on the particular software. 

Thank you in advance.

**Comment by bathomas** [comment]
Dear @ELENI93, 

I'm afraid there isn't a tutorial/getting started guide yet. I'm more than happy to give advice if you'd like to describe what you wish to do. If you'd prefer not to discuss your project in public, then feel free to email me at b.a.thomas [at] ucl.ac.uk.

Kind regards,

Ben
