### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by anbai106** [UCL/PETPVC#25]
Hi, I am trying to install PETPVC on my MAC, after installing ITK successfully, I try to follow the steps you wrote on github, but I get some error when doing make in the BUILD folder,
[ 71%] Building CXX object src/CMakeFiles/pvc_make4d.dir/Make4D.cxx.o
/Users/junhao.wen/Software/PETPVC/PETPVC/src/Make4D.cxx:33:10: fatal error:
      'itkLabelGeometryImageFilter.h' file not found

I am not familiar with cmake, can you help me?

Thanks in advance

**Comment by bathomas** [comment]
Hi,

This file belongs to the [ITK Review module](https://itk.org/Doxygen/html/group__ITKReview.html). When you build ITK, you need to switch on ```Module_ITKReview```. This should solve the problem. Please let us know if this works for you.
