### ISSUE TITLE
PETImageType::Pointer

### ISSUE THREAD

**Issue by rijobro** [UCL/PETPVC#33]
For me compilation was failing due to 
`PETImageType::Pointer outputImage = NULL;`
I rectified this by simply not setting it equal to NULL, i.e.:
`PETImageType::Pointer outputImage;`
No idea if this is safe, but it meant that I could complete compilation and start using the package.

**Comment by KrisThielemans** [comment]
C++11 issue.see for instance http://en.cppreference.com/w/cpp/language/nullptr. Would need to check what the pointer constructor does.

**Comment by bathomas** [comment]
I think removing the `NULL` will likely cause `petpvc` to crash if the user requests the `GTM` or `Labbe` method ([here](https://github.com/UCL/PETPVC/blob/25e05a1cef06ba93bd9fcca39466bc7360737607/src/PETPVC.cxx#L1265)).  This could of course be handled better with a `bool` etc.. I'm reluctant to enforce C++11 at this time.

**Comment by KrisThielemans** [comment]
would need to rely on preprocessor stuff. That's [tricky](https://stackoverflow.com/questions/10717502/is-there-a-preprocessor-directive-for-detecting-c11x-support) but possibly easier by using CMake and its C++ feature detection stuff (which I don't know).

**Comment by bathomas** [comment]
I wasn't thinking of anything so 'fancy'. More like:
```
isOutputImageReady = false;
...
outputImage = filter->GetOutput();
isOutputImageReady = true;
...
if ( isOutputImageReady ) {

}
```
