### ISSUE TITLE
Uninformative error message opening file

### ISSUE THREAD

**Issue by rijobro** [UCL/PETPVC#34]
Using the `petpvc` executable, I'm getting an error opening the input file. Even in Debug mode, the error isn't overly informative:
```
[Error]	Cannot read PET input file: /Users/rich/Documents/Data/MCIR/Output-MCIR/7_AC/AC_g4.nii
```
The file definitely exists and I can open it with other packages. I haven't checked the source code to figure out what the error is, but would a different message be possible (e.g., "could not locate file" if that were the problem).

**Comment by bathomas** [comment]
`petpvc` now displays `itk` exception information when file does not exist or cannot be read.
