### ISSUE TITLE
fatal error: localMetaConfiguration.h: No such file or directory

### ISSUE THREAD

**Issue by mrahimpour** [UCL/PETPVC#36]
Hi, Thanks for sharing your code!
I am trying to install the toolbox from source instruction. There is a compilation error as follows: 

masoomeh:~/opt/dev-tools-sources/PETPVC/BUILD$ make
[  3%] Linking CXX executable pvc_compareImages
/usr/bin/ld: cannot find -lITKDeprecated
collect2: error: ld returned 1 exit status
test/CMakeFiles/pvc_compareImages.dir/build.make:238: recipe for target 'test/pvc_compareImages' failed
make[2]: *** [test/pvc_compareImages] Error 1
CMakeFiles/Makefile2:92: recipe for target 'test/CMakeFiles/pvc_compareImages.dir/all' failed
make[1]: *** [test/CMakeFiles/pvc_compareImages.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

I am using Ubuntu 16.04, CMake 3.12.1, G++ compiler and double checked to build ITK 4.13 with Module_ITKReview ON. I will be grateful if you have any idea to solve this!

**Comment by bathomas** [comment]
I haven't tried to build with ITK 5 yet, so am not that surprised that there could be a problem. However, the two issues with 5 and 4.13 appear to be different. You're earlier post (before edit) with ITK 5 appears to be a missing header file, whereas on 4.13 the module `ITKDeprecated` was not found. Can you try enabling `Module_ITKDeprecated` in ITK's cmake, rebuild ITK and then try to compile `PETPVC`?

**Comment by mrahimpour** [comment]
I uninstalled ITK-5.0, enabled Module_ITKDeprecated on ITK-4.13; now it is working very well for me! Thanks for your help.
