### ISSUE TITLE
Toolbox installation problem

### ISSUE THREAD

**Issue by nanditajo** [UCL/PETPVC#42]
Hi, I am trying to install PETPVC on my Mac, running OS X 10.10.5. I have installed ITK successfully, while also having turned on the Module_ITKReview during the build. However, I get the following error: 

[  3%] Building CXX object test/CMakeFiles/pvc_compareImages.dir/CompareImages.cxx.o
make[2]: *** No rule to make target `/Applications/ITK_install/Build/lib/libitkdouble-conversion-4.13.a', needed by `test/pvc_compareImages'.  Stop.
make[1]: *** [test/CMakeFiles/pvc_compareImages.dir/all] Error 2
make: *** [all] Error 2

I know that this indicates some missing file during the ITK build, but I am not sure if I was supposed to enable any more modules? I enabled the ITK default modules and the ITKReview module during the configuration step.

I am using XCode 2.7.11 for compiling. Any help will be appreciated. Thanks in advance.

**Comment by bathomas** [comment]
Hi,

First thing I would do is to build ITK with `BUILD_TESTING=On`. Then issue `make test` in your ITK build directory and confirm that ITK is fine. If that is successful, then try running `make VERBOSE=true` in your PETPVC build directory and see if there is any more information.

**Comment by nanditajo** [comment]
Hi,

It turned out that I had to install double-conversion on Mac OSX. I dowloaded it from http://macappstore.org/double-conversion/ and then rebuilt ITK and it seemed to work perfectly for me! Thanks for the help.

- Nandita
