### ISSUE TITLE
PET header error

### ISSUE THREAD

**Issue by nanditajo** [UCL/PETPVC#43]
Hi, 

I am trying to apply the iterative Yang for PVC. I prepared the input files according to the instructions, but somethign seems to be wrong with the PET header file. The PET is coregistered to the MRI space and I also tried fslcpgeom between the two, however, I seem to get the following error:

petpvc -i /Users/nj/build13/test/sub.mc.mrcoreg.nii -m /Users/nj/build13/test/sub_mask.nii -o /Users/nj/build13/test/sub.PVC.nii --pvc IY -x 6.0 -y 6.0 -z 6.0 [--debug]
Too many arguments specified in your command line! Skipping extra argument: [--debug]
WARNING: In /Users/nj/ITK01/Modules/IO/MRC/src/itkMRCHeaderObject.cxx, line 140
MRCHeaderObject (0x7fcf1c007400): Some header data does not have sensable values

[Error]	Cannot read PET input file: /Users/nj/build13/test/sub.mc.mrcoreg.nii

itk::ExceptionObject (0x7fcf1af09dd8)
Location: "unknown" 
File: /Users/nj/ITK01/Modules/IO/MRC/src/itkMRCImageIO.cxx
Line: 250
Description: itk::ERROR: MRCImageIO(0x7fcf1af08230): Unrecognized header

I am not sure what the header needs contain for it to be recognized. Any help will be appreciated. Thanks!

**Comment by bathomas** [comment]
Try renaming `/Users/nj/build13/test/sub.mc.mrcoreg.nii` to something like `Users/nj/build13/test/sub_mc_mrcoreg.nii`. Also, `--debug` does not need the braces around it. This was to signify that `--debug` is a optional flag.

**Comment by nanditajo** [comment]
Replacing the '.' with '-' worked! Thank you so much.
