### ISSUE TITLE
Version disagreement in master versus release 1.2.4

### ISSUE THREAD

**Issue by justbennet** [UCL/PETPVC#49]
It appears that the version number for the release of 1.2.4 got bumped in CMakeLists.txt

https://github.com/UCL/PETPVC/commit/1845da5f0ed131590490e770c2706550a480e068

but that did not make it back to the master branch, which still shows version 1.2.2 and the last commit as

https://github.com/UCL/PETPVC/commit/0495d02904be3b811ff2880899e8f9cf2885031a

which is the parent of the release commit.

Just in case you would wish to have them agree.

**Comment by bathomas** [comment]
Cheers!
