### ISSUE TITLE
Parameter in RL-PVC

### ISSUE THREAD

**Issue by ubersexualShupeng** [UCL/PETPVC#54]
Nice work on the implementation of PVC algorithms.
In the PMB paper (PETPVC: a toolbox for performing partial volume correction techniques in positron emission tomography), formula (8), the alpha parameter is the step-size. What is the exact value used in the algorithm in the tool? Can I change it?
Thanks.

**Comment by bathomas** [comment]
Formula 8 refers to RVC rather than RL. The default step size is `1.5`. You can modify this by passing the `-a` or `--alpha` switch. If incorportating the `VanCittertPVCImageFilter` into your own code, then you set it via the `SetAlpha` method.
