### ISSUE TITLE
PETPVC does not build with ITK 5

### ISSUE THREAD

**Issue by bathomas** [UCL/PETPVC#55]
`itk::CylinderSpatialObject` does not seem to exist in ITK 5 and so `CreateTestImage.cxx` cannot be built.

**Comment by KrisThielemans** [comment]
https://discourse.itk.org/t/replacement-for-cylinderspatialobject/3771/2 suggests https://itk.org/Doxygen/html/classitk_1_1TubeSpatialObject.html
