### ISSUE TITLE
Van-Cittert deconvolution: Should be able to disable non-negativity constraint

### ISSUE THREAD

**Issue by HarryMarquis** [UCL/PETPVC#56]
Non-negativity constraint is imposed on the VC deconvolution method. It would be useful to be able to easily switch this on/off.

**Comment by bathomas** [comment]
@HarryMarquis can you try out the [non-neg](https://github.com/UCL/PETPVC/tree/non-neg) branch? To disable the constraint, use the command line argument: `--disable-non-neg`.
