### ISSUE TITLE
64-bit Windows release?

### ISSUE THREAD

**Issue by rullator** [UCL/PETPVC#59]
Is there also a pre-compiled release for Windows 64-bit available? The current version seems to be only 32-bit.

Or any other hints, why PETPVC runs out of memory?
In comparison, a self-compiled version (running Linux) processes the file without any problems.

```
     [Error]	Cannot read mask input file: T1_LMCI_002_S_1155_2012-12-20_1x1x1_Hammers_4d.nii
     
     itk::MemoryAllocationError (012FF3DC)
     Location: "unknown" 
     File: c:\projects\deps\itk-4.10.1\include\itk-4.10\itkImportImageContainer.hxx
     Line: 199
     Description: Failed to allocate memory for image.

```

**Comment by AJG-P** [comment]
I have the same kind of error... I have used the pre-built binaries for Windows. Do you know if this problem exists in the self-compiled version on windows?
 
[Error] failure applying STC on: r_frame3_1

itk::MemoryAllocationError (0113F1D8)
Location: "unknown"
File: c:\projects\deps\itk-4.10.1\include\itk-4.10\itkImportImageContainer.hxx
Line: 199
Description: Failed to allocate memory for image.

**Comment by bathomas** [comment]
Hi,

Yes. If you are able to compile a 64-bit version and use ITK 4.13 or maybe even v5, then this should no longer be an issue. I will eventually fix appveyor.

**Comment by margaretthompson** [comment]
Has there been any update on this issue? I am using a self-compiled version on Linux with ITK 4.13 and getting the same error as above. Are there known minimum requirements for the machine being used to run PETPVC?
