### ISSUE TITLE
Change number of iteration of RL with petpvc

### ISSUE THREAD

**Issue by ubersexualShupeng** [UCL/PETPVC#60]
Hi,

Nice implementation of PVC tool. 
It is an essential tool for quantitative PET imaging in clinical applications. 

We doing some experiments using the Richardson-Lucy algorithm in PETPVC.
**Could you let us know how to change the number of iterations?** Currently, we only use the default setting with iteration always = 10.
Thanks.

SChen

**Comment by KrisThielemans** [comment]
This is a bug in `petpvc` unfortunately. However, as a work-around you can do it via the dedicated executable:
```sh
petvc_rl -x 6 -y 6 -z 9 -i 5 blur.nii.gz RL5.nii.gz
```
will run for 5 iterations

**Comment by bathomas** [comment]
Does the `-k` switch not work when running `petpvc`?

**Comment by KrisThielemans** [comment]
aha, yes, it does. The `-i` switch doesn't. This then seems to just be a confusion between the 2 options. Where is `number of iterations` used. Iterative Yang? Why have 2 different options?

**Comment by bathomas** [comment]
I debated this for a while. I use `-i` for iterations of iterative Yang, but `-k` for number of iterations during a deconvolution i.e. Richardson-Lucy or van-Cittert. This enables the combination of techniques, such as iterative Yang followed by RL. This is confusing and the confusion it introduces is possibly not worth the flexibility.

**Comment by KrisThielemans** [comment]
ok. I think we should address this by just improving the documentation then (e.g. usage message)
