### ISSUE TITLE
PVC correction using GTM

### ISSUE THREAD

**Issue by TimZaragori** [UCL/PETPVC#65]
For the PVC correction using GTM, the latter is computed as
![image](https://user-images.githubusercontent.com/40388619/93020635-6be5f980-f5de-11ea-9ba7-6c9ca73122d6.png)  with vj being the total volume of ROIj and RSFi being the regional spread function for ROIi according to [1]. 
However in https://github.com/UCL/PETPVC/blob/master/lib/petpvcGTMImageFilter.txx#L161 it seems that the contribution of ROIi in ROIj is normalized by the number of voxels in ROIi instead of the number of voxels in ROIj. Is there a trick there that I am misunderstanding? 

[1] Rousset OG, Ma Y, Evans AC (1998) Correction for partial volume effects in PET: principle and validation. J Nucl Med 39:904-911

**Comment by KrisThielemans** [comment]
I haven't checked this carefully, but this looks like a choice in normalisation factor. As GTM does return the correct ROI values, I suspect that this is an arbitrary choice, so I'll close the issue. Feel free to reopen if you don't agree.
