### ISSUE TITLE
Help with petpvc installation

### ISSUE THREAD

**Issue by afendrich** [UCL/PETPVC#66]
Getting this error when trying to run petpvc:

`/home/ssd/petpvc/bin/petpvc: error while loading shared libraries: libITKIOBruker-4.13.so.1: cannot open shared object file: No such file or directory
`

Anyone have any luck getting this installed and working on their system lately?

**Comment by KrisThielemans** [comment]
Looks like you need to set your `LD_LIBRARY_PATH` to wherever you ITK libraries are installed.
```sh
export LD_LIBRARY_PATH=/wherever/:$LD_LIBRARY_PATH`
petpvc
```

**Comment by afendrich** [comment]
Thank you so much!
