### ISSUE TITLE
Submit a conda-forge recipe

### ISSUE THREAD

**Issue by ghisvail** [UCL/PETPVC#72]
Just a heads-up that I intend to submit a [conda-forge recipe](https://github.com/conda-forge/staged-recipes/pull/15045) for PETPVC.

Please let me know if you'd like to be added to the list of co-maintainers.

For now, it requires #71 to be merged and a new point release to be made :pray:

**Comment by KrisThielemans** [comment]
Great. thanks! I don't need to be added as maintainer. Ping me if you need me to at some point in the future.

@bathomas could you take care of creating a patch release?

**Comment by ghisvail** [comment]
The conda-forge package is ready for review. Could you at least tag the current tip of master so I can use it for the basis of the conda-forge package instead of backporting patches on top of v1.2.6?

Cheers.

**Comment by KrisThielemans** [comment]
done. also created releases. No idea if the deployment will work.

**Comment by ghisvail** [comment]
https://anaconda.org/conda-forge/petpvc
