### ISSUE TITLE
warnings on missing `override`

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/PETPVC#74]
When using ITK 5.2.0, CLang warns 
https://travis-ci.com/github/UCL/PETPVC/jobs/509265841#L3996-L3999
```
/Users/travis/build/UCL/PETPVC/lib/petpvcGTMImageFilter.h:84:18: warning: 'GenerateData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
```
Not sure when `override` was introduced. in ITK but presumably we need a version check

**Comment by ghisvail** [comment]
That's because version 5 uses [C++11](https://en.cppreference.com/w/cpp/language/override).

**Comment by ghisvail** [comment]
You can probably get away with [ITK_OVERRIDE](https://github.com/InsightSoftwareConsortium/ITK/commit/671d04333f5c43c82bc9aabab92f2d66140e653e).

**Comment by ghisvail** [comment]
Let me try a draft PR and we'll see if the warnings disappear on travis.

**Comment by ghisvail** [comment]
^ ready for review
