### ISSUE TITLE
Error building docker

### ISSUE THREAD

**Issue by mfdezp11** [UCL/PETPVC#83]
Hello,

I have been trying to build the docker image but when I was building it using the Dockerfile I got the following error :

![image](https://user-images.githubusercontent.com/102722399/162161539-fef2c484-ed20-4d30-a79f-43800da6cfb8.png)
![image](https://user-images.githubusercontent.com/102722399/162161629-1aaf86fa-8273-492c-b138-620bfafe4682.png)

I thougth this bug was related to alpine version, so I upgraded Alpine version to 3.12. This bug was fixed but a new bug appeared when compiling ITK:

![image](https://user-images.githubusercontent.com/102722399/162163696-af3c1cac-e1bf-47df-9aeb-82f00f168f3d.png)

Thanks

**Comment by mfdezp11** [comment]
Thanks a lot, it works

**Comment by bathomas** [comment]
Happy to accept a PR if you want.
