### ISSUE TITLE
Error in installing the PETPVC

### ISSUE THREAD

**Issue by Riiiico** [UCL/PETPVC#96]
I installed ITK software version 5.3.0 . I encounter this error when installing the PETPVC software:

 Could not find a package configuration file provided by "ITK" with any of
  the following names:
    ITKConfig.cmake
    itk-config.cmake
  Add the installation prefix of "ITK" to CMAKE_PREFIX_PATH or set "ITK_DIR"
  to a directory containing one of the above files.  If "ITK" provides a
  separate development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!

I followed the instruction in [https://stackoverflow.com/questions/35027316/itk-cannot-find-itkconfig-cmake]
but the same error has accrued.
Can someone help me please?

**Comment by KrisThielemans** [comment]
Hi, this is standard CMake behaviour if it cannot find an installed package. The CMake variable `ITK_DIR` has to be set where `ITKConfig.cmake` is. On my system, I have to do
```sh
cmake -DITK_DIR:PATH=/home/kris/devel/install/lib/cmake/ITK-5.2/ <normal options>
```
If you don't know where it is, on most Linux versions, you can do `locate ITKConfig.cmake`.
This is because I have built ITK myself, with `CMAKE_INSTALL_PREFIX=~/devel/install`.

Obviously, you'll have to adjust the path to you situation. It has to be the location where

**Comment by KrisThielemans** [comment]
> No source or binary directory provided

This seems to say you ran `cmake` without specify the source (or build). In old-style, once you are in the build directory you can do
```sh
cmake <options> .
```
(i.e. a trailing `.` for "the current directory"). In new style, you specify build dir with `-B` or `--build`:
```sh
cmake <options> -B .
```
> CMake Error: The source directory "C:/ITK/Build" does not appear to contain CMakeLists.txt

I don't understand this. there has to be something wrong with your command line/where you run this.

> The ITKConfig.cmake is in the "C:/ITK/Build" directory

You probably don't want to use that one. Did you install ITK as well? (I recommend doing that). In your case, something like
```
cd c:/ITK/Build
cmake --build . --target install --config Release
```

If this doesn't help, can you be even more explicit in the steps you follow, including commands executed where.

Finally, note that you can download a precompiled version of petpvc, or use https://anaconda.org/conda-forge/petpvc

**Comment by Riiiico** [comment]
Where can I download the precompiled version?

**Comment by KrisThielemans** [comment]
I've updated the README to make that a bit more obvious.
https://github.com/UCL/PETPVC/blob/master/README.md

**Comment by Riiiico** [comment]
Thank you very much Kris,
I installed it via conda.
