### ISSUE TITLE
help　for　install　problem

### ISSUE THREAD

**Issue by yahuiZhanguping** [UCL/PETPVC#97]
I encountered the following problem during the installation. I have no idea where to find this makefile. I don't really understand these. I hope someone can answer. Thank you very much.  
![Uploading problem.PNG…]()

**Comment by yahuiZhanguping** [comment]
The `makefile` file was not found in the BUILD folder.

**Comment by KrisThielemans** [comment]
Something went wrong with the upload of your picture, so I have no idea what your error is. (Ideally you copy text or a log file, but fine).

In any case, can you describe steps followed? Brief install instructions are at https://github.com/UCL/PETPVC/?tab=readme-ov-file#building-and-installing. You might need to get yourself familiar with basic CMake. Or get one of the binarires, or use conda.

**Comment by yahuiZhanguping** [comment]
I'm very excited to receive your reply. I ran the `cmake` command on Windows. I found the relevant information that `cmake` generates `.sln` by default on Windows instead of `makefile`. Using `cmake -G "Unix Makefiles"..` can generate `makefile` on Windows, but the following error occurred when executing the `make` command 。
[  3%] Building CXX object test/CMakeFiles/pvc_createTestImage.dir/CreateTestImage.cxx.obj
c++.exe: error: /bigobj: No such file or directory
test/CMakeFiles/pvc_createTestImage.dir/build.make:76: recipe for target 'test/CMakeFiles/pvc_createTestImage.dir/CreateTestImage.cxx.obj' failed
make[2]: *** [test/CMakeFiles/pvc_createTestImage.dir/CreateTestImage.cxx.obj] Error 1
CMakeFiles/Makefile2:143: recipe for target 'test/CMakeFiles/pvc_createTestImage.dir/all' failed
make[1]: *** [test/CMakeFiles/pvc_createTestImage.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

So I successfully installed PETPVC through conda. Thank you very much for your reply. I wish you a happy life and all the best.

**Comment by KrisThielemans** [comment]
ok. For future ref, if you generate a `.sln`, then you will need to use Visual Studio to compile ("open project" in CMake).

**Comment by yahuiZhanguping** [comment]
Hello. I would like to ask how long it takes to correct an image. I used the RL and MTC methods respectively, and there was no waiting at all. I used it for the correction of tumor PET images and felt no difference.
