### ISSUE TITLE
"/usr/bin/ld: cannot find -lGTest::Main: No such file or directory" while trying to compile petpvc

### ISSUE THREAD

**Issue by orenshaniathuji** [UCL/PETPVC#99]
Hi All,

I am trying to compile petpvc via spack and I get an error while compiling the sources, which doesn't seem to be related to spack but to the code itself:

( I am compiling with  gcc-12.2.0

  >> 577    /usr/bin/ld: cannot find -lGTest::GTest: No such file or directory
  >> 578    /usr/bin/ld: cannot find -lGTest::Main: No such file or directory
  >> 579    collect2: error: ld returned 1 exit status
  >> 580    make[2]: *** [src/CMakeFiles/petpvc.dir/build.make:206: src/petpvc] Error 1
     581    make[2]: Leaving directory '/tmp/hurcs_dev/spack-stage/spack-stage-petpvc-1.2.11-utmlhtvxo4au4ue3oq5teulllvzgelq4/spack-build-utmlhtv'
  >> 582    make[1]: *** [CMakeFiles/Makefile2:459: src/CMakeFiles/petpvc.dir/all] Error 2
     583    make[1]: Leaving directory '/tmp/hurcs_dev/spack-stage/spack-stage-petpvc-1.2.11-utmlhtvxo4au4ue3oq5teulllvzgelq4/spack-build-utmlhtv'
  >> 584    make: *** [Makefile:169: all] Error 2

This occurs with several gcc commands and while it seems that no GTests are defind anywhere.

Please check and let me know how I can fix.

Many thanks,

Oren

**Comment by KrisThielemans** [comment]
I don't know spac at all I'm afraid. I see you're using CMake, which uses "imported targets" https://cmake.org/cmake/help/latest/module/FindGTest.html.

As PETPVC doesn't use GTest at all, I have no idea what we could do to help you fix your problem.

**Comment by haampie** [comment]
The issue is https://github.com/InsightSoftwareConsortium/ITK/issues/303

**Comment by orenshaniathuji** [comment]
Thank you Harmen,

The problem was indeed with ITK and I was able to overcome it.

BR

Oren
